-- MySQL Script generated by MySQL Workbench
-- Qua 30 Mar 2016 08:58:35 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tb_pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_pais` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NULL,
  `sigla` VARCHAR(10) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`tb_cadastro_endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_cadastro_endereco` (
  `id` INT NOT NULL,
  `tipo_endereco` VARCHAR(45) NULL,
  `endereco` VARCHAR(45) NULL,
  `complemento` VARCHAR(45) NULL,
  `cep` VARCHAR(14) NULL,
  `bairro` VARCHAR(45) NULL,
  `telefone` VARCHAR(10) NULL,
  `fk_pais_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_cadastro_endereco_tb_pais1_idx` (`fk_pais_id` ASC),
  CONSTRAINT `fk_tb_cadastro_endereco_tb_pais1`
    FOREIGN KEY (`fk_pais_id`)
    REFERENCES `mydb`.`tb_pais` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`tb_cadastro_plano`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_cadastro_plano` (
  `id` INT NOT NULL,
  `nome_plano` VARCHAR(80) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`tb_cadastro_paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_cadastro_paciente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_pac` VARCHAR(45) NULL,
  `cpf_pac` VARCHAR(14) NULL,
  `cod_plano` INT NULL,
  `email_pac` VARCHAR(45) NULL,
  `nascimento_pac` DATE NULL,
  `sexo_pac` VARCHAR(1) NULL,
  `fk_endereco_id` INT NOT NULL,
  `fk_plano_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_cadastro_paciente_tb_cadastro_endereco1_idx` (`fk_endereco_id` ASC),
  INDEX `fk_tb_cadastro_paciente_cadastro_plano1_idx` (`fk_plano_id` ASC),
  CONSTRAINT `fk_tb_cadastro_paciente_tb_cadastro_endereco1`
    FOREIGN KEY (`fk_endereco_id`)
    REFERENCES `mydb`.`tb_cadastro_endereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_cadastro_paciente_cadastro_plano1`
    FOREIGN KEY (`fk_plano_id`)
    REFERENCES `mydb`.`tb_cadastro_plano` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_categoria` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`tb_sintomas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_sintomas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_sitomas` VARCHAR(255) NULL,
  `fk_categoria_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_sintomas_tb_categoria1_idx` (`fk_categoria_id` ASC),
  CONSTRAINT `fk_tb_sintomas_tb_categoria1`
    FOREIGN KEY (`fk_categoria_id`)
    REFERENCES `mydb`.`tb_categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`tb_medidas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_medidas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_area_medida` VARCHAR(80) NULL,
  `unidade_medida` DOUBLE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`tb_estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_estado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(75) NULL,
  `uf` VARCHAR(5) NULL,
  `fk_pais_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_estado_tb_pais_idx` (`fk_pais_id` ASC),
  CONSTRAINT `fk_tb_estado_tb_pais`
    FOREIGN KEY (`fk_pais_id`)
    REFERENCES `mydb`.`tb_pais` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pais` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NULL DEFAULT NULL,
  `sigla` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estado` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(75) NULL DEFAULT NULL,
  `uf` VARCHAR(5) NULL DEFAULT NULL,
  `pais` INT(7) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Estado_pais` (`pais` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 28
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cidade` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(120) NULL DEFAULT NULL,
  `estado` INT(5) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Cidade_estado` (`estado` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 5565
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`tb_cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_cidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(75) NULL,
  `fk_estado_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_cidade_tb_estado1_idx` (`fk_estado_id` ASC),
  CONSTRAINT `fk_tb_cidade_tb_estado1`
    FOREIGN KEY (`fk_estado_id`)
    REFERENCES `mydb`.`tb_estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`tb_sintomas_pacientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_sintomas_pacientes` (
  `fk_sintomas_id` INT NOT NULL,
  `fk_cadastro_paciente_id` INT NOT NULL,
  PRIMARY KEY (`fk_sintomas_id`, `fk_cadastro_paciente_id`),
  INDEX `fk_tb_sintomas_has_tb_cadastro_paciente_tb_cadastro_pacient_idx` (`fk_cadastro_paciente_id` ASC),
  INDEX `fk_tb_sintomas_has_tb_cadastro_paciente_tb_sintomas1_idx` (`fk_sintomas_id` ASC),
  CONSTRAINT `fk_tb_sintomas_has_tb_cadastro_paciente_tb_sintomas1`
    FOREIGN KEY (`fk_sintomas_id`)
    REFERENCES `mydb`.`tb_sintomas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_sintomas_has_tb_cadastro_paciente_tb_cadastro_paciente1`
    FOREIGN KEY (`fk_cadastro_paciente_id`)
    REFERENCES `mydb`.`tb_cadastro_paciente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`tb_medidas_paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_medidas_paciente` (
  `fk_cadastro_paciente_id` INT NOT NULL,
  `fk_medidas_id` INT NOT NULL,
  PRIMARY KEY (`fk_cadastro_paciente_id`, `fk_medidas_id`),
  INDEX `fk_tb_cadastro_paciente_has_tb_medidas_tb_medidas1_idx` (`fk_medidas_id` ASC),
  INDEX `fk_tb_cadastro_paciente_has_tb_medidas_tb_cadastro_paciente_idx` (`fk_cadastro_paciente_id` ASC),
  CONSTRAINT `fk_tb_cadastro_paciente_has_tb_medidas_tb_cadastro_paciente1`
    FOREIGN KEY (`fk_cadastro_paciente_id`)
    REFERENCES `mydb`.`tb_cadastro_paciente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_cadastro_paciente_has_tb_medidas_tb_medidas1`
    FOREIGN KEY (`fk_medidas_id`)
    REFERENCES `mydb`.`tb_medidas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`password_resets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`password_resets` (
  `email` VARCHAR(255) NOT NULL,
  `token` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `remember_token` VARCHAR(100) NULL,
  `created_at` TIMESTAMP NULL,
  `update_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
